name: myportfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  universal_platform: ^1.1.0
  universal_html: ^2.2.4
  http: ^1.2.2


dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets\icon\amaljose_icon.png'      
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets\icon\amaljose_icon.png'
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: 'assets\icon\amaljose_icon.png'
    icon_size: 48 
  macos:
    generate: true
    image_path: 'assets\icon\amaljose_icon.png'
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true 

  assets:
    - assets/images/
    - assets/images/projects/ 
    - assets/fonts/
    - assets/pdf/

     

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: BonaNovaSC
      fonts:
        - asset: assets/fonts/BonaNovaSC-Regular.ttf 
